name: SimpleLoggerPlugin
main: kengonakajima.test.plugin.simplelogger.SimpleLoggerPlugin
version: 0.0.1
api-version: 1.16

commands:
  setgreeting:
    description: set greeting message
    usage: /setgreeting message text
  cleargreeting:
    description: clear greeting message
    usage: /cleargreeting
